Peer2peer.Web/Models/Layout/AlertViewModel.cs
namespace Peer2peer.Web.Models.Layout
{
    public class AlertViewModel
    {
        public const string Key = "alerts";
        public const string Success = "success";
        public const string Error = "error";
        public const string Info = "info";

        public string Title { get; set; }
        public string Type { get; set; }
        public string Message { get; set; }

        public string Layout => Type == Success ? "top" : "bottom";
    }
}

Peer2peer.Web/Models/Layout/LanguageSelectionViewModel.cs
using System.Collections.Generic;
using Abp.Localization;

namespace Peer2peer.Web.Models.Layout
{
    public class LanguageSelectionViewModel
    {
        public LanguageInfo CurrentLanguage { get; set; }

        public IReadOnlyList<LanguageInfo> Languages { get; set; }
    }
}

Peer2peer.Web/Models/Layout/TopMenuViewModel.cs
using Abp.Application.Navigation;

namespace Peer2peer.Web.Models.Layout
{
    public class TopMenuViewModel
    {
        public UserMenu MainMenu { get; set; }

        public string ActiveMenuItemName { get; set; }
    }
}

Peer2peer.Web/Models/Layout/UserMenuOrLoginLinkViewModel.cs
using Peer2peer.Sessions.Dto;

namespace Peer2peer.Web.Models.Layout
{
    public class UserMenuOrLoginLinkViewModel
    {
        public GetCurrentLoginInformationsOutput LoginInformations { get; set; }
        public bool IsMultiTenancyEnabled { get; set; }

        public string GetShownLoginName()
        {
            return LoginInformations.User.UserName;
        }

        public UserLoginInfoDto User => LoginInformations.User;
    }
}

Peer2peer.Web/Areas/Cp/Controllers/PackagesController.cs
using System.Linq;
using System.Web.Mvc;
using Abp.Authorization;
using Abp.Domain.Repositories;
using Abp.Timing;
using Peer2peer.Peering;
using Peer2peer.Peering.Dto;
using Peer2peer.Users;
using Peer2peer.Web.Controllers;

namespace Peer2peer.Web.Areas.Cp.Controllers
{
    public class PackagesController : BackendControllerBase
    {
        private readonly IRepository<PackageType> _packageTypeRepository;
        private readonly IRepository<Package> _packageRepository;
        private readonly IDonationAppService _donationService;

        public PackagesController(IUserAppService userAppService,
            IRepository<Package> packageRepository, IRepository<PackageType> packageTypeRepository,
            IDonationAppService donationAppService):base(userAppService)
        {
            _packageTypeRepository = packageTypeRepository;
            _packageRepository = packageRepository;
            _donationService = donationAppService;
        }

        // GET: Cp/Packages
        public ActionResult Index()
        {
            return RedirectToAction("Index", "Dashboard", new { area = "Cp" });
        }

        [AbpAuthorize]
        public ActionResult Create(string id)
        {
            if (_packageRepository.GetAll().Any(p => p.UserId == AbpSession.UserId.Value && p.Status == Status.Pending))
            {
                FlashError("Please wait for your current circle to be completed");
                return RedirectToAction("Index", "Dashboard");
            }
            var name = id;
            var packageType = _packageTypeRepository.FirstOrDefault(p => p.Name == name.ToLower());

            if (packageType == null)
            {
                FlashError("Invalid package selected");
                return RedirectToAction("Index", "Dashboard");
            }

            var package = new Package
            {
                UserId = AbpSession.UserId.Value,
                ExpectedRi = packageType.ReturnOnInvestment,
                CurrentRi = 0,
                TypeId = packageType.Id,
                Status = Status.Pending,
                CreatedDate = Clock.Now
            };

            _packageRepository.Insert(package);
            FlashSuccess("Your package have been added. Please wait to be paired");
            return RedirectToAction("Index", "Dashboard");
        }

        public ActionResult Confirm(int donationId, string t = "p")
        {
            var result = _donationService.ConfirmDonation(new ConfirmDonationInput {DonationId = donationId,
                CurrentUserId = AbpSession.UserId.Value, Type = t
            });
            if(result.Success) FlashSuccess(result.Message);
            else FlashError(result.Message);
            return RedirectToAction("Index", "Dashboard", new {area = "Cp"});
        }

        public ActionResult ChangeStatus(int donationId, string status = Status.AwaitingAlert, string t = "p")
        {
            var result =
                _donationService.ChangeDonationStatus(new ChangeDonationStatusInput
                {
                    DonationId = donationId,
                    Status = status,
                    CurrentUserId = AbpSession.UserId.Value,
                    Type = t
                });
            if (result.Success) FlashSuccess(result.Message);
            else FlashError(result.Message);
            return RedirectToAction("Index", "Dashboard", new {area = "Cp"});
        }
    }
}

Peer2peer.Web/Controllers/LayoutController.cs
using System.Web.Mvc;
using Abp.Application.Navigation;
using Abp.Configuration.Startup;
using Abp.Localization;
using Abp.Runtime.Session;
using Abp.Threading;
using Peer2peer.Sessions;
using Peer2peer.Web.Models.Layout;

namespace Peer2peer.Web.Controllers
{
    public class LayoutController : Peer2peerControllerBase
    {
        private readonly IUserNavigationManager _userNavigationManager;
        private readonly ISessionAppService _sessionAppService;
        private readonly IMultiTenancyConfig _multiTenancyConfig;
        private readonly ILanguageManager _languageManager;

        public LayoutController(
            IUserNavigationManager userNavigationManager, 
            ISessionAppService sessionAppService, 
            IMultiTenancyConfig multiTenancyConfig,
            ILanguageManager languageManager)
        {
            _userNavigationManager = userNavigationManager;
            _sessionAppService = sessionAppService;
            _multiTenancyConfig = multiTenancyConfig;
            _languageManager = languageManager;
        }

        [ChildActionOnly]
        public PartialViewResult TopMenu(string activeMenu = "")
        {
            var model = new TopMenuViewModel
                        {
                            MainMenu = AsyncHelper.RunSync(() => _userNavigationManager.GetMenuAsync("MainMenu", AbpSession.ToUserIdentifier())),
                            ActiveMenuItemName = activeMenu
                        };

            return PartialView("_TopMenu", model);
        }

        [ChildActionOnly]
        public PartialViewResult LanguageSelection()
        {
            var model = new LanguageSelectionViewModel
                        {
                            CurrentLanguage = _languageManager.CurrentLanguage,
                            Languages = _languageManager.GetLanguages()
                        };

            return PartialView("_LanguageSelection", model);
        }

        [ChildActionOnly]
        public PartialViewResult UserMenuOrLoginLink()
        {
            UserMenuOrLoginLinkViewModel model;

            if (AbpSession.UserId.HasValue)
            {
                model = new UserMenuOrLoginLinkViewModel
                {
                    LoginInformations = AsyncHelper.RunSync(() => _sessionAppService.GetCurrentLoginInformations()),
                    IsMultiTenancyEnabled = _multiTenancyConfig.IsEnabled,
                };
            }
            else
            {
                model = new UserMenuOrLoginLinkViewModel
                {
                    IsMultiTenancyEnabled = _multiTenancyConfig.IsEnabled                    
                };
            }

            return PartialView("_UserMenuOrLoginLink", model);
        }

        [ChildActionOnly]
        public PartialViewResult MonachTopBar()
        {
            UserMenuOrLoginLinkViewModel model;

            if (AbpSession.UserId.HasValue)
            {
                model = new UserMenuOrLoginLinkViewModel
                {
                    LoginInformations = AsyncHelper.RunSync(() => _sessionAppService.GetCurrentLoginInformations()),
                    IsMultiTenancyEnabled = _multiTenancyConfig.IsEnabled,
                };
            }
            else
            {
                model = new UserMenuOrLoginLinkViewModel
                {
                    IsMultiTenancyEnabled = _multiTenancyConfig.IsEnabled
                };
            }

            return PartialView("__MonachTopBar", model);
        }

        [ChildActionOnly]
        public PartialViewResult MonachSideBar(string activeMenu = "")
        {
            var model = new TopMenuViewModel
            {
                MainMenu = AsyncHelper.RunSync(() => _userNavigationManager.GetMenuAsync("SideMenu", AbpSession.ToUserIdentifier())),
                ActiveMenuItemName = activeMenu
            };

            return PartialView( model);
        }
    }
}

Peer2peer.Web/Views/Shared/_Layout.cshtml
@using System.Threading
@using System.Web.Optimization
@using Abp.Timing
@using Abp.Web.Mvc.Extensions
@using Peer2peer
@{
    SetAntiForgeryCookie();
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="shortcut icon" href="~/favicon.ico">

    <title>@AppConstants.AppName</title>

    @Styles.Render("~/Bundles/vendor/css")
    @Styles.Render("~/Bundles/css")

    <!-- View specific styles -->
    @RenderSection("styles", required: false)

    <script type="text/javascript">
        //This is used to get the application's root path from javascript. It's useful if you're running application in a virtual directory under IIS.
        var abp = abp || {}; abp.appPath = '@ApplicationPath';
    </script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="@Url.Content("~/Scripts/others/html5shiv.js")"></script>
        <script src="@Url.Content("~/Scripts/others/respond.min.js")"></script>
    <![endif]-->

    @Scripts.Render("~/Bundles/vendor/js/top")

</head>
<body style="background: lightgray">
    @*@Html.Partial("_TopBar")*@

    <div class="container">
        @RenderBody()
    </div>

    @Scripts.Render("~/Bundles/vendor/js/bottom")
    @Scripts.Render("~/Bundles/js")

    <script>
        //Localizing momentjs
        moment.locale('@Thread.CurrentThread.CurrentUICulture.Name');
    </script>

    <!-- Dynamic scripts of ABP system (They are created on runtime and can not be bundled) -->
    <script src="~/api/AbpServiceProxies/GetAll?v=@(Clock.Now.Ticks)"></script>
    <script src="~/AbpScripts/GetScripts?v=@(Clock.Now.Ticks)" type="text/javascript"></script>

    <!-- SignalR scripts -->
    <script src="~/signalr/hubs"></script>
    @Html.IncludeScript("~/Abp/Framework/scripts/libs/abp.signalr.js")

<!-- View specific scripts -->
    @RenderSection("scripts", required: false)
    
    
    
    <!--Start of Tawk.to Script-->
    <script type="text/javascript">
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/58dbd67af7bbaa72709c312e/default';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
    </script>
    <!--End of Tawk.to Script-->
    

</body>
</html>

Peer2peer.Web/Views/Shared/_MonachFrontendLayout.cshtml
@using Abp.Timing
@using Peer2peer
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        /* Loading Spinner */
        .spinner{margin:0;width:70px;height:18px;margin:-35px 0 0 -9px;position:absolute;top:50%;
        left:50%;text-align:center}.spinner > div{width:18px;height:18px;background-color:#333;
        border-radius:100%;display:inline-block;-webkit-animation:bouncedelay 1.4s infinite ease-in-out;
        animation:bouncedelay 1.4s infinite ease-in-out;-webkit-animation-fill-mode:both;
        animation-fill-mode:both}.spinner .bounce1{-webkit-animation-delay:-.32s;
        animation-delay:-.32s}.spinner .bounce2{-webkit-animation-delay:-.16s;animation-delay:-.16s}
        @@-webkit-keyframes
         bouncedelay{0%,80%,100%{-webkit-transform:scale(0.0)}40%{-webkit-transform:scale(1.0)}}
        @@keyframes bouncedelay{0%,80%,100%{transform:scale(0.0);
        -webkit-transform:scale(0.0)}40%{transform:scale(1.0);-webkit-transform:scale(1.0)}}
    </style>
    <meta charset="UTF-8">
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
    <title> @ViewBag.Title | @AppConstants.AppName </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <!-- Favicons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="~/Content/monarch/assets/images/icons/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="~/Content/monarch/assets/images/icons/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="~/Content/monarch/assets/images/icons/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="~/Content/monarch/assets/images/icons/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="~/Content/monarch/assets/images/icons/favicon.png">

    <link rel="stylesheet" type="text/css" href="~/Content/monarch/assets-minified/frontend-all-demo.css">
    <!-- JS Core -->
    <script type="text/javascript" src="~/Content/monarch/assets-minified/js-core.js"></script>

    <script type="text/javascript">
    $(window).load(function(){
        setTimeout(function() {
            $('#loading').fadeOut( 400, "linear" );
        }, 300);
    });
    </script>
</head>
<body>
    <div id="loading">
        <div class="spinner">
            <div class="bounce1"></div>
            <div class="bounce2"></div>
            <div class="bounce3"></div>
        </div>
    </div>
    <div id="page-wrapper">
        <div class="top-bar bg-topbar">
            <div class="container">
                <div class="float-left">
                    <a href="#" class="btn btn-sm bg-facebook tooltip-button" data-placement="bottom" title="Follow us on Facebook">
                        <i class="glyph-icon icon-facebook"></i>
                    </a>
                    <a href="#" class="btn btn-sm bg-google tooltip-button" data-placement="bottom" title="Follow us on Google+">
                        <i class="glyph-icon icon-google-plus"></i>
                    </a>
                    <a href="#" class="btn btn-sm bg-twitter tooltip-button" data-placement="bottom" title="Follow us on Twitter">
                        <i class="glyph-icon icon-twitter"></i>
                    </a>
                    <a href="#" class="btn btn-top btn-sm" title="Give us a call">
                        <i class="glyph-icon icon-phone"></i>
                        +08034832738
                    </a>
                </div>
                <div class="float-right user-account-btn dropdown">
                    <a href="@Url.Action("Index", "Dashboard", new{area = "Cp"})" title="Go to your member area" 
                       class="btn btn-sm float-left btn-alt btn-hover mrg10R btn-default">
                        <span>Go to Control Panel</span>
                        <i class="glyph-icon icon-arrow-right"></i>
                    </a> 
                    <a class="btn btn-sm float-left btn-alt btn-hover mrg10R btn-default" href="@Url.Action("Login", "Account", new {area = ""})">Login</a>
                    <a  class="btn btn-sm float-left btn-alt btn-hover mrg10R btn-default" href="@Url.Action("Register", "Account", new {area = ""})">Register</a>
                </div>
            </div><!-- .container -->
        </div><!-- .top-bar -->
        <div class="main-header wow fadeInDown bg-blue font-inverse">
            <div class="container">
                <a href="@Url.Action("Index", "Home", new {area = ""})" class="header-logo" 
                   title="Home Page">@AppConstants.AppName</a><!-- .header-logo -->
                
                <ul class="header-nav collapse">
                    <li>
                        <a href="@Url.Action("Index", "Home", new {area = ""})" title="Homepages">
                            Homepages
                            <i class="glyph-icon icon-home"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#" title="How It Works">
                            How It Works
                            <i class="glyph-icon icon-info"></i>
                        </a>
                    </li>
                </ul><!-- .header-nav -->
            </div><!-- .container -->
        </div><!-- .main-header -->
        <!-- Owl carousel -->
        <!--<link rel="stylesheet" type="text/css" href="~/Content/monarch/assets/widgets/owlcarousel/owlcarousel.css">-->
        <script type="text/javascript" src="~/Content/monarch/assets/widgets/owlcarousel/owlcarousel.js"></script>
        <script type="text/javascript" src="~/Content/monarch/assets/widgets/owlcarousel/owlcarousel-demo.js"></script>
    
        @RenderBody()
    
        <div class="main-footer bg-gradient-4 clearfix">
            <div class="footer-pane">
                <div class="container clearfix">
                    <div class="logo">&copy; @Clock.Now.Year @AppConstants.AppName. All Rights Reserved.</div>
                    <div class="footer-nav-bottom">
                        <a href="@Url.Action("Index", "Home")" title="Home">Home Page</a>
                        <a href="#" title="Layout">How It Works</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- JS Demo -->
    <script type="text/javascript" src="~/Content/monarch/assets-minified/frontend-all-demo.js"></script>
</body>
</html>

Peer2peer.Web/Views/Shared/_MonachLayout.cshtml
@using System.Threading
@using System.Web.Optimization
@using Abp.Timing
@using Peer2peer
@using Peer2peer.Web.Models.Layout
@{
    SetAntiForgeryCookie();
}

<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        /* Loading Spinner */
        .spinner{margin:0;width:70px;height:18px;margin:-35px 0 0 -9px;position:absolute;
        top:50%;left:50%;text-align:center}.spinner > div{width:18px;height:18px;background-color:#333;
        border-radius:100%;display:inline-block;-webkit-animation:bouncedelay 1.4s infinite ease-in-out;
        animation:bouncedelay 1.4s infinite ease-in-out;-webkit-animation-fill-mode:both;
        animation-fill-mode:both}.spinner .bounce1{-webkit-animation-delay:-.32s;
        animation-delay:-.32s}.spinner .bounce2{-webkit-animation-delay:-.16s;
        animation-delay:-.16s}@@-webkit-keyframes bouncedelay{0%,80%,100%{-webkit-transform:scale(0.0)}40%{-webkit-transform:scale(1.0)}}
        @@keyframes bouncedelay {
            0%,80%,100% {
                transform: scale(0.0);
                -webkit-transform: scale(0.0);
            }

            40% {
                transform: scale(1.0);
                -webkit-transform: scale(1.0);
            }
        }
    </style>

    <meta charset="UTF-8">
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
    <title> @AppConstants.AppName - @ViewBag.Title </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <!-- Favicons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="~/Content/monarch/assets/images/icons/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="~/Content/monarch/assets/images/icons/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="~/Content/monarch/assets/images/icons/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="~/Content/monarch/assets/images/icons/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="~/Content/monarch/assets/images/icons/favicon.png">
    
    <!-- View specific styles -->
    @RenderSection("styles", required: false)

    <script type="text/javascript">
        //This is used to get the application's root path from javascript. It's useful if you're running application in a virtual directory under IIS.
        var abp = abp || {}; abp.appPath = '@ApplicationPath';
    </script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="@Url.Content("~/Scripts/others/html5shiv.js")"></script>
        <script src="@Url.Content("~/Scripts/others/respond.min.js")"></script>
    <![endif]-->

    @Scripts.Render("~/Bundles/vendor/js/top")

    <link rel="stylesheet" type="text/css" href="~/Content/monarch/assets-minified/admin-all-demo.css">
    <!-- JS Core -->
    <script type="text/javascript" src="~/Content/monarch/assets-minified/js-core.js"></script>


    <script type="text/javascript">
        $(window).load(function(){
            setTimeout(function() {
                $('#loading').fadeOut( 400, "linear" );
            }, 300);
        });
    </script>

</head>

<body>
    <div id="sb-site">
        

        <div id="loading">
            <div class="spinner">
                <div class="bounce1"></div>
                <div class="bounce2"></div>
                <div class="bounce3"></div>
            </div>
        </div>
        <div id="page-wrapper">
            
            @*@Html.Partial("_MonachTopTab")*@
            @*@Html.Partial("_MonachSideBar")*@
            @Html.Action("MonachTopBar", "Layout", new {area=""})
            @Html.Action("MonachSideBar", "Layout", new {area=""})
            
            @RenderBody()
        </div>

        <!-- JS Demo -->
        <script type="text/javascript" src="~/Content/monarch/assets-minified/admin-all-demo.js"></script>

        @*@Scripts.Render("~/Bundles/vendor/js/bottom")
        @Scripts.Render("~/Bundles/js")*@

        @if (TempData[AlertViewModel.Key] != null)
        {
            var alerts = (List<AlertViewModel>)TempData[AlertViewModel.Key];
            foreach (var alert in alerts)
            {
                <script type="text/javascript" src="~/Content/monarch/assets/widgets/noty-notifications/noty.js"></script>
                  <script>
                      noty({
                          text: '@alert.Message <a href="#" class"btn-blue-alt btn btn-md display-block">Close</a>',
                          type: '@alert.Type',
                          dismissQueue: true,
                          theme: "agileUI",
                          layout: '@alert.Layout'
                      });
            </script>
             }
           
        }

        <script>
            //Localizing momentjs
            moment.locale('@Thread.CurrentThread.CurrentUICulture.Name');
        </script>

        <!-- Dynamic scripts of ABP system (They are created on runtime and can not be bundled) -->
        <script src="~/api/AbpServiceProxies/GetAll?v=@(Clock.Now.Ticks)"></script>
        <script src="~/AbpScripts/GetScripts?v=@(Clock.Now.Ticks)" type="text/javascript"></script>
        
        <!-- View specific scripts -->
        @RenderSection("scripts", required: false)
    </div>
</body>
</html>

Peer2peer.Web/Views/Shared/_MonachSideBar.cshtml
<div id="page-sidebar">
    <div class="scroll-sidebar">

        <ul id="sidebar-menu">
        @*if this is an admin*@
            <li class="header"><span>Administration</span></li>
            <li>
                <a href="/backbone" title="Admin Dashboard">
                    <i class="glyph-icon icon-linecons-diamond"></i>
                    <span>Admin dashboard</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Pending", "Packages", new {area = "Backbone"})" title="New Packages">
                    <i class="glyph-icon icon-linecons-diamond"></i>
                    <span>New Packages</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Confirmed", "Packages", new { area = "Backbone"})" title="Confirmed Packages">
                    <i class="glyph-icon icon-linecons-diamond"></i>
                    <span>Confirmed Packages</span>
                </a>
            </li>
            <li class="divider"></li>

            <li class="header"><span>Members Area</span></li>
            <li>
                <a href="/cp" title="Control Panel">
                    <i class="glyph-icon icon-linecons-tv"></i>
                    <span>Control Panel</span>
                </a>
            </li>
        </ul><!-- #sidebar-menu -->

    </div>
</div>

Peer2peer.Web/Views/Shared/_TopBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="~/"><i class="fa fa-cubes"></i> Peer2peer</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                @Html.Action("TopMenu", "Layout", new { activeMenu = ViewBag.ActiveMenu })
            </ul>
            <ul class="nav navbar-nav navbar-right">
                @Html.Action("LanguageSelection", "Layout")
                @Html.Action("UserMenuOrLoginLink", "Layout")
            </ul>
        </div>
    </div>
</div>